# Generated by Django 5.2.11 on 2026-02-19 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Выручка')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Прибыль')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во продаж')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во заказов')),
                ('avg_check', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средний чек')),
                ('new_customers', models.PositiveIntegerField(default=0, verbose_name='Новых клиентов')),
                ('write_offs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Списания')),
            ],
            options={
                'verbose_name': 'Дневная сводка',
                'verbose_name_plural': 'Дневные сводки',
                'db_table': 'daily_summaries',
                'ordering': ['-date'],
            },
        ),
    ]
