# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='trading_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.tradingpoint', verbose_name='Торговая точка'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('trading_point', 'date')},
        ),
    ]
