# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'db_table': 'inventory_documents',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ожидаемое')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактическое')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Разница')),
            ],
            options={
                'verbose_name': 'Позиция инвентаризации',
                'verbose_name_plural': 'Позиции инвентаризации',
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Резерв',
                'verbose_name_plural': 'Резервы',
                'db_table': 'reserves',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество')),
                ('avg_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средняя закупочная')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'db_table': 'stock_balances',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('receipt', 'Приход'), ('write_off', 'Списание'), ('transfer', 'Перемещение'), ('sale', 'Продажа'), ('return', 'Возврат'), ('adjustment', 'Корректировка'), ('assembly', 'Сборка букета')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('write_off_reason', models.CharField(blank=True, choices=[('expired', 'Срок годности'), ('damaged', 'Повреждён'), ('lost', 'Утеря'), ('defect', 'Брак'), ('other', 'Другое')], default='', max_length=20, verbose_name='Причина списания')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Движение товара',
                'verbose_name_plural': 'Движения товаров',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закупочная цена')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток')),
                ('arrival_date', models.DateField(verbose_name='Дата прихода')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Годен до')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер накладной')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'db_table': 'batches',
                'ordering': ['-arrival_date'],
            },
        ),
    ]
