# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('nomenclature', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='batch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_documents', to=settings.AUTH_USER_MODEL, verbose_name='Проводил'),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_documents', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_documents', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorydocument', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='sales.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.batch', verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='core.warehouse', verbose_name='Склад-отправитель'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='core.warehouse', verbose_name='Склад-получатель'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbalance',
            unique_together={('warehouse', 'nomenclature')},
        ),
    ]
