# Generated by Django 5.2.11 on 2026-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockbalance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='batch_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('organization', 'warehouse', 'nomenclature'), name='unique_stock_balance_per_org_warehouse_nomenclature'),
        ),
    ]
