# Generated by Django 6.0.2 on 2026-02-28 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tradingpoint_unique_trading_point_name_per_org_and_more'),
        ('inventory', '0003_alter_stockbalance_unique_together_and_more'),
        ('nomenclature', '0006_alter_nomenclaturegroup_parent'),
        ('sales', '0004_sale_cash_shift'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.sale', verbose_name='Продажа'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'warehouse', 'nomenclature', 'remaining'], name='idx_batch_fifo'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'movement_type', 'sale'], name='idx_movement_org_type_sale'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'nomenclature', 'created_at'], name='idx_movement_org_nom_date'),
        ),
    ]
