# Generated by Django 5.2.11 on 2026-03-02 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tradingpoint_unique_trading_point_name_per_org_and_more'),
        ('inventory', '0005_protect_fks'),
        ('nomenclature', '0006_alter_nomenclaturegroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
    ]
