# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorydocument_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorydocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Инвентаризация', 'verbose_name_plural': 'Инвентаризации'},
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ['-created_at'], 'verbose_name': 'Резерв', 'verbose_name_plural': 'Резервы'},
        ),
        migrations.AlterModelOptions(
            name='stockbalance',
            options={'ordering': ['warehouse', 'nomenclature'], 'verbose_name': 'Остаток', 'verbose_name_plural': 'Остатки'},
        ),
    ]
