# Generated by Django 6.0.2 on 2026-03-20 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_organization_options_and_more'),
        ('customers', '0003_alter_customeraddress_options_and_more'),
        ('inventory', '0007_alter_inventorydocument_options_and_more'),
        ('nomenclature', '0009_remove_nomenclaturegroup_sort_order'),
        ('sales', '0010_alter_orderitem_nomenclature_and_more'),
        ('suppliers', '0002_alter_supplier_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetBatchComponentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accounting_type', models.CharField(blank=True, default='stock_material', max_length=20, verbose_name='Тип учёта')),
                ('quantity_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кол-во на 1 букет')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед.')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('source_mode', models.CharField(choices=[('template', 'Из шаблона'), ('manual', 'Ручная сборка'), ('correction', 'Коррекция')], default='template', max_length=20, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Снимок состава букета',
                'verbose_name_plural': 'Снимки составов букетов',
                'db_table': 'bouquet_batch_component_snapshots',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(verbose_name='Номер поступления')),
                ('date', models.DateField(verbose_name='Дата поступления')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Документ поступления',
                'verbose_name_plural': 'Документы поступлений',
                'db_table': 'receipt_documents',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDocumentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закупочная цена')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена продажи')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость итого')),
            ],
            options={
                'verbose_name': 'Строка документа поступления',
                'verbose_name_plural': 'Строки документов поступлений',
                'db_table': 'receipt_document_items',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='nomenclature',
        ),
        migrations.AddField(
            model_name='batch',
            name='is_assembly',
            field=models.BooleanField(default=False, verbose_name='Сборка букета'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='inventory.batch', verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='bouquet_nomenclature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='nomenclature.nomenclature', verbose_name='Номенклатура букета'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='customers.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок резерва'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='phone_last4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Последние 4 цифры'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='phone_normalized',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон (нормализованный)'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='reserve_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер резерва'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Продано'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='sold_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_reserves', to='sales.sale', verbose_name='Продажа'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('sold', 'Продан'), ('expired', 'Просрочен'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='trading_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='core.tradingpoint', verbose_name='Торговая точка'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='sales.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AddIndex(
            model_name='reserve',
            index=models.Index(fields=['phone_last4'], name='idx_reserve_phone_last4'),
        ),
        migrations.AddIndex(
            model_name='reserve',
            index=models.Index(fields=['organization', 'status'], name='idx_reserve_org_status'),
        ),
        migrations.AddField(
            model_name='bouquetbatchcomponentsnapshot',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_snapshots', to='inventory.batch', verbose_name='Партия букета'),
        ),
        migrations.AddField(
            model_name='bouquetbatchcomponentsnapshot',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.nomenclature', verbose_name='Номенклатура компонента'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_documents', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_documents', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='batch',
            name='receipt_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.receiptdocument', verbose_name='Документ поступления'),
        ),
        migrations.AddField(
            model_name='receiptdocumentitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_document_items', to='inventory.batch', verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='receiptdocumentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.receiptdocument', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='receiptdocumentitem',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='receiptdocumentitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.AddConstraint(
            model_name='receiptdocument',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='unique_receipt_number_per_org'),
        ),
    ]
