# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.organization', verbose_name='Организация')),
                ('trading_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.tradingpoint', verbose_name='Торговая точка')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='PayrollScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('hourly', 'Почасовая'), ('shift', 'За смену'), ('percent_sales', '% от продаж'), ('mixed', 'Смешанная')], default='fixed', max_length=20, verbose_name='Тип')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Базовая сумма')),
                ('sales_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% от продаж')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('started_at', models.DateField(verbose_name='Начало действия')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_schemes', to='staff.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Схема оплаты',
                'verbose_name_plural': 'Схемы оплаты',
                'db_table': 'payroll_schemes',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Базовая ставка')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'positions',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.position', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='SalaryAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оклад/тариф')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бонус')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Штраф')),
                ('sales_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бонус с продаж')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Утверждено'), ('paid', 'Выплачено')], default='pending', max_length=20, verbose_name='Статус')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_accruals', to='staff.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_accruals', to='core.organization', verbose_name='Организация')),
                ('paid_from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.wallet', verbose_name='Выплачено из кошелька')),
            ],
            options={
                'verbose_name': 'Начисление зарплаты',
                'verbose_name_plural': 'Начисления зарплаты',
                'db_table': 'salary_accruals',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='Перерыв (мин)')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.organization', verbose_name='Организация')),
                ('trading_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.tradingpoint', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'db_table': 'shifts',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
