# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_delete_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollscheme',
            options={'ordering': ['-started_at'], 'verbose_name': 'Схема оплаты', 'verbose_name_plural': 'Схемы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
