# Generated by Django 6.0.2 on 2026-02-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=5, verbose_name='Макс. пользователей'),
        ),
        migrations.AddField(
            model_name='organization',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ежемесячная плата'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='organization',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Оплачено до'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('basic', 'Базовый'), ('pro', 'Профессиональный'), ('enterprise', 'Корпоративный')], default='free', max_length=20, verbose_name='Тарифный план'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_organization',
            field=models.ForeignKey(blank=True, help_text='Для суперадминов: организация, от имени которой ведётся работа.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.organization', verbose_name='Активная организация'),
        ),
    ]
