# Generated by Django 6.0.2 on 2026-02-24 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_is_active_organization_max_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Контактное лицо тенанта',
                'verbose_name_plural': 'Контактные лица тенантов',
                'db_table': 'tenant_contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('call', 'Звонок'), ('meeting', 'Встреча'), ('support', 'Тех. поддержка'), ('billing', 'Биллинг'), ('internal', 'Внутренняя заметка'), ('onboarding', 'Онбординг'), ('other', 'Другое')], default='internal', max_length=20, verbose_name='Тип')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenant_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_notes', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Заметка по тенанту',
                'verbose_name_plural': 'Заметки по тенантам',
                'db_table': 'tenant_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('period_from', models.DateField(verbose_name='Период с')),
                ('period_to', models.DateField(verbose_name='Период по')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Банковский перевод'), ('card', 'Банковская карта'), ('cash', 'Наличные'), ('other', 'Другое')], default='bank_transfer', max_length=20, verbose_name='Способ оплаты')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер счёта')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_tenant_payments', to=settings.AUTH_USER_MODEL, verbose_name='Записал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Оплата тенанта',
                'verbose_name_plural': 'Оплаты тенантов',
                'db_table': 'tenant_payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
