# Generated by Django 6.0.2 on 2026-02-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentmethod_wallet_warehouse_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_trading_point',
            field=models.ForeignKey(blank=True, help_text='Торговая точка, в контексте которой работает пользователь.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.tradingpoint', verbose_name='Активная торговая точка'),
        ),
    ]
