# Generated by Django 5.2.11 on 2026-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_employee_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tradingpoint',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_trading_point_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('organization', 'trading_point', 'name'), name='unique_warehouse_name_per_trading_point'),
        ),
    ]
