# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tradingpoint_unique_trading_point_name_per_org_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='tradingpoint',
            options={'ordering': ['name'], 'verbose_name': 'Торговая точка', 'verbose_name_plural': 'Торговые точки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
    ]
