# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход'), ('transfer', 'Перевод между кошельками'), ('salary', 'Зарплата'), ('personal_expense', 'Личный расход сотрудника'), ('supplier_payment', 'Оплата поставщику')], max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('direction', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Направление')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная')),
            ],
            options={
                'verbose_name': 'Категория транзакций',
                'verbose_name_plural': 'Категории транзакций',
                'db_table': 'transaction_categories',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('wallet_type', models.CharField(choices=[('cash', 'Наличные (касса)'), ('bank_account', 'Расчётный счёт'), ('card', 'Корпоративная карта'), ('personal_card', 'Личная карта сотрудника'), ('online', 'Онлайн-оплата'), ('other', 'Другое')], default='cash', max_length=20, verbose_name='Тип')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Баланс')),
                ('allow_negative', models.BooleanField(default=False, verbose_name='Допускать отрицательный баланс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debt_type', models.CharField(choices=[('supplier', 'Поставщик'), ('employee', 'Сотрудник'), ('customer', 'Клиент'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('direction', models.CharField(choices=[('we_owe', 'Мы должны'), ('owed_to_us', 'Нам должны')], max_length=20, verbose_name='Направление')),
                ('counterparty_name', models.CharField(max_length=255, verbose_name='Контрагент')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Оплачено')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'db_table': 'debts',
            },
        ),
    ]
