# Generated by Django 6.0.2 on 2026-02-28 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tradingpoint_unique_trading_point_name_per_org_and_more'),
        ('finance', '0004_transaction_employee_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Время открытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('balance_at_open', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Остаток при открытии')),
                ('expected_balance_at_close', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ожидаемый остаток')),
                ('actual_balance_at_close', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Фактический остаток')),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Расхождение')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Открыл')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='core.organization', verbose_name='Организация')),
                ('trading_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='core.tradingpoint', verbose_name='Торговая точка')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='finance.wallet', verbose_name='Касса (Кошелёк)')),
            ],
            options={
                'verbose_name': 'Кассовая смена',
                'verbose_name_plural': 'Кассовые смены',
                'db_table': 'cash_shifts',
                'ordering': ['-opened_at'],
            },
        ),
    ]
