# Generated by Django 5.2.11 on 2026-03-02 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_unique_customer_phone_per_org'),
        ('finance', '0009_wallet_wallet_balance_positive_or_allowed'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='customers.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='debt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
    ]
