# Generated by Django 6.0.2 on 2026-03-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_debt_customer_debt_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Долг', 'verbose_name_plural': 'Долги'},
        ),
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория транзакций', 'verbose_name_plural': 'Категории транзакций'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['name'], 'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.transactioncategory', verbose_name='Родительская категория'),
        ),
    ]
