# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('nomenclature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Адрес')),
                ('inn', models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН')),
                ('payment_terms', models.CharField(blank=True, default='', max_length=255, verbose_name='Условия оплаты')),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок доставки (дней)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Мин. сумма заказа')),
                ('rating', models.PositiveSmallIntegerField(default=3, verbose_name='Рейтинг (1-5)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='open', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма претензии')),
                ('resolved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Компенсация')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Фотографии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='inventory.batch', verbose_name='Партия')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.organization', verbose_name='Организация')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Претензия',
                'verbose_name_plural': 'Претензии',
                'db_table': 'claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('confirmed', 'Подтверждён'), ('shipped', 'Отгружен'), ('received', 'Получен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='core.organization', verbose_name='Организация')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заказ поставщику',
                'verbose_name_plural': 'Заказы поставщикам',
                'db_table': 'supplier_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Получено')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.supplierorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа поставщику',
                'verbose_name_plural': 'Позиции заказов поставщикам',
                'db_table': 'supplier_order_items',
            },
        ),
        migrations.CreateModel(
            name='SupplierNomenclature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_sku', models.CharField(blank=True, default='', max_length=50, verbose_name='Артикул поставщика')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Мин. кол-во')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товар поставщика',
                'verbose_name_plural': 'Товары поставщиков',
                'db_table': 'supplier_nomenclatures',
                'unique_together': {('supplier', 'nomenclature')},
            },
        ),
    ]
