# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='suppliernomenclature',
            options={'ordering': ['supplier', 'nomenclature'], 'verbose_name': 'Товар поставщика', 'verbose_name_plural': 'Товары поставщиков'},
        ),
        migrations.AlterModelOptions(
            name='supplierorderitem',
            options={'ordering': ['order'], 'verbose_name': 'Позиция заказа поставщику', 'verbose_name_plural': 'Позиции заказов поставщикам'},
        ),
    ]
