# Generated by Django 5.2.11 on 2026-02-19 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('courier_type', models.CharField(choices=[('internal', 'Штатный'), ('external', 'Внешний'), ('service', 'Курьерская служба')], default='internal', max_length=20, verbose_name='Тип')),
                ('vehicle', models.CharField(blank=True, default='', max_length=100, verbose_name='Транспорт')),
                ('delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка за доставку')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
                'db_table': 'couriers',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('assigned', 'Назначена'), ('picked_up', 'Забрана'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('failed', 'Не доставлена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Получатель')),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон получателя')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='С')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='До')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('courier_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата курьеру')),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='deliveries/', verbose_name='Фото доставки')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'db_table': 'deliveries',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('free_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Бесплатно от (сумма заказа)')),
                ('estimated_minutes', models.PositiveIntegerField(default=60, verbose_name='Время доставки (мин)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
                'db_table': 'delivery_zones',
            },
        ),
    ]
