# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('delivery', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_profile', to='staff.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='courier',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.courier', verbose_name='Курьер'),
        ),
    ]
