# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('delivery', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliveryzone', verbose_name='Зона'),
        ),
    ]
