# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_courier_employee_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={'ordering': ['name'], 'verbose_name': 'Курьер', 'verbose_name_plural': 'Курьеры'},
        ),
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['name'], 'verbose_name': 'Зона доставки', 'verbose_name_plural': 'Зоны доставки'},
        ),
    ]
