# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'db_table': 'measure_units',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('nomenclature_type', models.CharField(choices=[('single_flower', 'Штучный цветок'), ('bouquet', 'Готовый букет'), ('composition', 'Композиция'), ('packaging', 'Упаковка'), ('accessory', 'Аксессуар'), ('ribbon', 'Лента'), ('toy', 'Игрушка'), ('postcard', 'Открытка'), ('extra_good', 'Сопутствующий товар'), ('balloon', 'Воздушный шар'), ('pot_plant', 'Горшечное растение'), ('service', 'Услуга')], default='single_flower', max_length=20, verbose_name='Тип')),
                ('sku', models.CharField(blank=True, default='', max_length=50, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, default='', max_length=50, verbose_name='Штрихкод')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Закупочная цена')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Розничная цена')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Минимальная цена')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Наценка %')),
                ('image', models.ImageField(blank=True, null=True, upload_to='nomenclature/', verbose_name='Фото')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Страна')),
                ('season_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Начало сезона (месяц)')),
                ('season_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Конец сезона (месяц)')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок годности (дней)')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='core.organization', verbose_name='Организация')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclature.measureunit', verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'db_table': 'nomenclatures',
            },
        ),
        migrations.CreateModel(
            name='BouquetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assembly_time_minutes', models.PositiveIntegerField(default=15, verbose_name='Время сборки (мин)')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, verbose_name='Сложность (1-5)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание сборки')),
                ('nomenclature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_template', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Шаблон букета',
                'verbose_name_plural': 'Шаблоны букетов',
                'db_table': 'bouquet_templates',
            },
        ),
        migrations.CreateModel(
            name='BouquetComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='nomenclature.bouquettemplate', verbose_name='Шаблон букета')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bouquets', to='nomenclature.nomenclature', verbose_name='Материал')),
                ('substitute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_in_bouquets', to='nomenclature.nomenclature', verbose_name='Замена')),
            ],
            options={
                'verbose_name': 'Компонент букета',
                'verbose_name_plural': 'Компоненты букетов',
                'db_table': 'bouquet_components',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature_groups', to='core.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nomenclature.nomenclaturegroup', verbose_name='Родительская группа')),
            ],
            options={
                'verbose_name': 'Группа номенклатуры',
                'verbose_name_plural': 'Группы номенклатуры',
                'db_table': 'nomenclature_groups',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures', to='nomenclature.nomenclaturegroup', verbose_name='Группа'),
        ),
    ]
