# Generated by Django 6.0.2 on 2026-02-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_active_trading_point'),
        ('nomenclature', '0003_remove_nomenclature_season_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquettemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_templates', to='core.organization', verbose_name='Организация'),
        ),
    ]
