# Generated by Django 6.0.2 on 2026-02-28 09:38

from django.db import migrations


def populate_template_org(apps, schema_editor):
    """Заполняем organization из связанной номенклатуры."""
    BouquetTemplate = apps.get_model('nomenclature', 'BouquetTemplate')
    for tpl in BouquetTemplate.objects.select_related('nomenclature').filter(organization__isnull=True):
        if tpl.nomenclature and tpl.nomenclature.organization_id:
            tpl.organization_id = tpl.nomenclature.organization_id
            tpl.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0004_add_org_to_bouquet_template'),
    ]

    operations = [
        migrations.RunPython(populate_template_org, migrations.RunPython.noop),
    ]
