# Generated by Django 5.2.11 on 2026-03-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0006_alter_nomenclaturegroup_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='shelf_life_days',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='default_shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок годности по умолчанию (дней)'),
        ),
    ]
