# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_organization_options_and_more'),
        ('nomenclature', '0007_remove_nomenclature_shelf_life_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Диаметр (см)'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='stem_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ростовка/Длина (см)'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['organization', 'nomenclature_type'], name='nomenclatur_organiz_7f1324_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='nomenclatur_organiz_f007bd_idx'),
        ),
    ]
