# Generated by Django 6.0.2 on 2026-03-20 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_organization_options_and_more'),
        ('nomenclature', '0009_remove_nomenclaturegroup_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закупочная цена')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История закупочной цены',
                'verbose_name_plural': 'История закупочных цен',
                'db_table': 'purchase_price_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bouquettemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bouquet_templates/', verbose_name='Фото шаблона'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='accounting_type',
            field=models.CharField(choices=[('stock_material', 'Складской материал'), ('finished_bouquet', 'Готовые букеты'), ('service', 'Услуги')], default='stock_material', max_length=20, verbose_name='Тип учёта'),
        ),
        migrations.AlterField(
            model_name='nomenclaturegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nomenclature.nomenclaturegroup', verbose_name='Родительская группа'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['organization', 'accounting_type'], name='nomenclatur_organiz_2b3e49_idx'),
        ),
        migrations.AddField(
            model_name='purchasepricehistory',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
    ]
