# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unknown', 'Не указан')], default='unknown', max_length=10, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Персональная скидка %')),
                ('bonus_points', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонусные баллы')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма покупок')),
                ('purchases_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во покупок')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='Метка')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес клиента',
                'verbose_name_plural': 'Адреса клиентов',
                'db_table': 'customer_addresses',
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка %')),
                ('color', models.CharField(blank=True, default='#3B82F6', max_length=7, verbose_name='Цвет метки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_groups', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Группа клиентов',
                'verbose_name_plural': 'Группы клиентов',
                'db_table': 'customer_groups',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customers', to='customers.customergroup', verbose_name='Группы'),
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('remind_days_before', models.PositiveIntegerField(default=3, verbose_name='Напомнить за (дней)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_dates', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Важная дата',
                'verbose_name_plural': 'Важные даты',
                'db_table': 'important_dates',
                'ordering': ['date'],
            },
        ),
    ]
