# Generated by Django 5.2.11 on 2026-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('organization', 'phone'), name='unique_customer_phone_per_org'),
        ),
    ]
