# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_unique_customer_phone_per_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-is_default', 'label'], 'verbose_name': 'Адрес клиента', 'verbose_name_plural': 'Адреса клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа клиентов', 'verbose_name_plural': 'Группы клиентов'},
        ),
    ]
