# Generated by Django 5.2.11 on 2026-02-19 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('channel_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип')),
                ('url', models.URLField(blank=True, default='', verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_channels', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Рекламный канал',
                'verbose_name_plural': 'Рекламные каналы',
                'db_table': 'ad_channels',
            },
        ),
        migrations.CreateModel(
            name='AdInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='marketing.adchannel', verbose_name='Канал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_investments', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Расход на рекламу',
                'verbose_name_plural': 'Расходы на рекламу',
                'db_table': 'ad_investments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная')], default='percent', max_length=10, verbose_name='Тип')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение')),
                ('apply_to', models.CharField(choices=[('all', 'Весь чек'), ('group', 'Группа товаров'), ('nomenclature', 'Конкретный товар')], default='all', max_length=20, verbose_name='Применять к')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Мин. сумма покупки')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('program_type', models.CharField(choices=[('bonus', 'Бонусная'), ('discount', 'Скидочная'), ('cashback', 'Кэшбэк')], default='bonus', max_length=20, verbose_name='Тип')),
                ('accrual_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='% начисления')),
                ('max_payment_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Макс. % оплаты бонусами')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Программа лояльности',
                'verbose_name_plural': 'Программы лояльности',
                'db_table': 'loyalty_programs',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Макс. использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='marketing.discount', verbose_name='Скидка')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promo_codes',
            },
        ),
    ]
