# Generated by Django 5.2.11 on 2026-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_promo_code_per_org'),
        ),
    ]
