# Generated by Django 6.0.2 on 2026-02-28 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_promocode_unique_promo_code_per_org'),
        ('nomenclature', '0006_alter_nomenclaturegroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='target_group',
            field=models.ForeignKey(blank=True, help_text='Заполнить при apply_to=group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='nomenclature.nomenclaturegroup', verbose_name='Целевая группа'),
        ),
        migrations.AddField(
            model_name='discount',
            name='target_nomenclature',
            field=models.ForeignKey(blank=True, help_text='Заполнить при apply_to=nomenclature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='nomenclature.nomenclature', verbose_name='Целевая номенклатура'),
        ),
    ]
