# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_discount_target_group_discount_target_nomenclature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adchannel',
            options={'ordering': ['name'], 'verbose_name': 'Рекламный канал', 'verbose_name_plural': 'Рекламные каналы'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['name'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'ordering': ['name'], 'verbose_name': 'Программа лояльности', 'verbose_name_plural': 'Программы лояльности'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['code'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
