# Generated by Django 6.0.2 on 2026-02-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка %'),
        ),
    ]
