# Generated by Django 5.2.11 on 2026-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_discount_percent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', '')), fields=('organization', 'number'), name='unique_sale_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', '')), fields=('organization', 'number'), name='unique_order_number_per_org'),
        ),
    ]
