# Generated by Django 6.0.2 on 2026-02-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_cashshift'),
        ('sales', '0003_sale_order_unique_numbers_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='finance.cashshift', verbose_name='Кассовая смена'),
        ),
    ]
