# Generated by Django 5.2.11 on 2026-03-02 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0007_remove_nomenclature_shelf_life_days_and_more'),
        ('sales', '0007_sales_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед.')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sales.orderitem', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Состав позиции заказа',
                'verbose_name_plural': 'Составы позиций заказов',
                'db_table': 'order_item_compositions',
            },
        ),
        migrations.CreateModel(
            name='SaleItemComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед.')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sales.saleitem', verbose_name='Позиция продажи')),
            ],
            options={
                'verbose_name': 'Состав позиции продажи',
                'verbose_name_plural': 'Составы позиций продаж',
                'db_table': 'sale_item_compositions',
            },
        ),
    ]
