# Generated by Django 5.2.11 on 2026-03-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_orderitemcomposition_saleitemcomposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ask_recipient_address',
            field=models.BooleanField(default=False, verbose_name='Уточнить адрес у получателя'),
        ),
    ]
