# Generated by Django 6.0.2 on 2026-03-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0008_nomenclature_deleted_at_nomenclature_diameter_and_more'),
        ('sales', '0009_order_ask_recipient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
    ]
