# Generated by Django 6.0.2 on 2026-03-20 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_organization_options_and_more'),
        ('inventory', '0008_bouquetbatchcomponentsnapshot_receiptdocument_and_more'),
        ('nomenclature', '0010_purchasepricehistory_bouquettemplate_image_and_more'),
        ('sales', '0010_alter_orderitem_nomenclature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.reserve', verbose_name='Резерв'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='source_mode',
            field=models.CharField(choices=[('catalog', 'Каталог'), ('ready_bouquet', 'Готовый букет'), ('reserve', 'Резерв')], default='catalog', max_length=20, verbose_name='Режим источника'),
        ),
        migrations.CreateModel(
            name='SalesCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Иконка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible_in_cashier', models.BooleanField(default=True, verbose_name='Видна в кассе')),
                ('source_type', models.CharField(choices=[('nomenclature', 'Номенклатура'), ('finished_bouquets', 'Готовые букеты'), ('reserve', 'Резерв')], default='nomenclature', max_length=20, verbose_name='Тип источника')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='sales_categories', to='nomenclature.nomenclaturegroup', verbose_name='Группы номенклатуры')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_categories', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Категория продаж',
                'verbose_name_plural': 'Категории продаж',
                'db_table': 'sales_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
